### ISSUE TITLE
Split off enroll plugin repo

### ISSUE THREAD

**Issue by kcaruso4** [jhu-sheridan-libraries/stfrancis-lutece-site#18]
- [ ] Cleanup
- [ ] Delete code from original repo
- [ ] Document build process in plugin repo
- [ ] Update documentation in original repo

**Comment by jrmartino** [comment]
plugin code has been cleaned up
testing procedure has been built and documented
original repo has had the plugin code removed, andplugin installation documentsd
new setup has been tested
