### ISSUE TITLE
Enroll plugin tests

### ISSUE THREAD

**Issue by kcaruso4** [jhu-sheridan-libraries/stfrancis-lutece-site#21]

**Comment by jrmartino** [comment]
tests have been written - still trying to get them to run doing thngs the lutece way. 
https://fr.lutece.paris.fr/fr/jsp/site/Portal.jsp?page=wiki&view=page&page_name=maven#H3_Run_unit_tests

**Comment by jrmartino** [comment]
tests uncovered some gas in the code - these have been addressed. tests now pass.
