### ISSUE TITLE
Creating a form generates an error

### ISSUE THREAD

**Issue by kcaruso4** [jhu-sheridan-libraries/stfrancis-lutece-site#24]
When creating a new form on the homepage of the admin site, an internal error is generated. Oddly enough when you create a form object on the public site through site administration, the form that caused an internal error appears as an option to be associated with the form object.

**Comment by htpvu** [comment]
Relating to this ticket? https://github.com/jhu-sheridan-libraries/stfrancis-lutece-site/issues/37

**Comment by htpvu** [comment]
No longer an issue.
