### ISSUE TITLE
Write up what best suggestion to present to Sayeed for deciding about requirements to handle personal information

### ISSUE THREAD

**Issue by cyork** [jhu-sheridan-libraries/stfrancis-lutece-site#42]
Understand of requirements for handling personal information

**Comment by jhujasonw** [comment]
I think part of writing something up is knowing a clear distinction of what data we are looking to be concerned with.  There was some speculation at a meeting about possibilities, but if the developers can tell me what data from end users we would be collecting, that would inform what a "best suggestion" for handling the data would be.

**Comment by jhujasonw** [comment]
Per Jim: Name, PhoneNumber, Email, Nothing Else.

**Comment by jhujasonw** [comment]
https://docs.google.com/document/d/1dIPrsDT4iU6RKuM8fQPnuS0izJlvvdIbEx6n3wHyi78/edit#heading=h.zhzdq6a4ztd0

**Comment by htpvu** [comment]
The current doc is in draft status. 
Reopened until it is in the form that can be sent to Sayeed. 
If no one comments on this within a week from today, it will be sent to sayeed as is.

**Comment by htpvu** [comment]
Document is ready to be sent to sayeed.
